### ISSUE TITLE
可用了吗？

### ISSUE THREAD

**Issue by ertuil** [Roarcannotprogramming/Auto-Fuck-the-Univ#1]
优秀的豪豪同学！

**Comment by Roarcannotprogramming** [comment]
可用 已部署到运行环境 今天已经全自动签到了
需要注意的是 最好自己抓个包 我这个发送的是我个人的信息 在武汉的 需要结合自己情况更改post的内容

**Comment by ertuil** [comment]
OK  我也调试好了 开了个 crontab。 感谢豪豪
（默默问一句为啥只能用 py2.7 啊）
